# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ..common import common_message_pb2 as v2_dot_common_dot_common__message__pb2
from . import kms_api_pb2 as v2_dot_kms_dot_kms__api__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v2/kms/kms_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyManagerServiceStub(object):
    """KeyManagerService creates cryptographic keys asynchronously.
    SK exists in memory only during generation -- wiped after sealing.
    Idempotent: calling with an existing key_id returns READY without
    re-generation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateKey = channel.unary_unary(
                '/kms.v2.KeyManagerService/GenerateKey',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.GenerateKeyRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.GenerateKeyResponse.FromString,
                _registered_method=True)
        self.GetKeyStatus = channel.unary_unary(
                '/kms.v2.KeyManagerService/GetKeyStatus',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.GetKeyStatusRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.GetKeyStatusResponse.FromString,
                _registered_method=True)
        self.GetKeyDetails = channel.unary_unary(
                '/kms.v2.KeyManagerService/GetKeyDetails',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.GetKeyDetailsRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.GetKeyDetailsResponse.FromString,
                _registered_method=True)
        self.DownloadKey = channel.unary_stream(
                '/kms.v2.KeyManagerService/DownloadKey',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.DownloadKeyRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.DownloadKeyResponse.FromString,
                _registered_method=True)
        self.TransitionState = channel.unary_unary(
                '/kms.v2.KeyManagerService/TransitionState',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.TransitionStateRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.TransitionStateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kms.v2.KeyManagerService/Delete',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.DeleteRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kms.v2.KeyManagerService/Health',
                request_serializer=v2_dot_common_dot_common__message__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=v2_dot_common_dot_common__message__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class KeyManagerServiceServicer(object):
    """KeyManagerService creates cryptographic keys asynchronously.
    SK exists in memory only during generation -- wiped after sealing.
    Idempotent: calling with an existing key_id returns READY without
    re-generation.
    """

    def GenerateKey(self, request, context):
        """Generate FHE Secret Key + derive EncKey/EvalKey + MetadataKey.
        Returns immediately with status=PENDING. Client polls GetKeyStatus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeyStatus(self, request, context):
        """Poll key generation status. Returns PENDING, READY, or FAILED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKeyDetails(self, request, context):
        """Return key version metadata for a given key_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadKey(self, request, context):
        """Download key material bytes by logical file type.
        Large keys are streamed in chunks to avoid gRPC unary message limits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransitionState(self, request, context):
        """Update key lifecycle state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete a key and its associated material.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKey,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.GenerateKeyRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.GenerateKeyResponse.SerializeToString,
            ),
            'GetKeyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeyStatus,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.GetKeyStatusRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.GetKeyStatusResponse.SerializeToString,
            ),
            'GetKeyDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKeyDetails,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.GetKeyDetailsRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.GetKeyDetailsResponse.SerializeToString,
            ),
            'DownloadKey': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadKey,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.DownloadKeyRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.DownloadKeyResponse.SerializeToString,
            ),
            'TransitionState': grpc.unary_unary_rpc_method_handler(
                    servicer.TransitionState,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.TransitionStateRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.TransitionStateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.DeleteRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.DeleteResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v2_dot_common_dot_common__message__pb2.HeartbeatRequest.FromString,
                    response_serializer=v2_dot_common_dot_common__message__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v2.KeyManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v2.KeyManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyManagerService(object):
    """KeyManagerService creates cryptographic keys asynchronously.
    SK exists in memory only during generation -- wiped after sealing.
    Idempotent: calling with an existing key_id returns READY without
    re-generation.
    """

    @staticmethod
    def GenerateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.KeyManagerService/GenerateKey',
            v2_dot_kms_dot_kms__api__pb2.GenerateKeyRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.GenerateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.KeyManagerService/GetKeyStatus',
            v2_dot_kms_dot_kms__api__pb2.GetKeyStatusRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.GetKeyStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKeyDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.KeyManagerService/GetKeyDetails',
            v2_dot_kms_dot_kms__api__pb2.GetKeyDetailsRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.GetKeyDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kms.v2.KeyManagerService/DownloadKey',
            v2_dot_kms_dot_kms__api__pb2.DownloadKeyRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.DownloadKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransitionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.KeyManagerService/TransitionState',
            v2_dot_kms_dot_kms__api__pb2.TransitionStateRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.TransitionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.KeyManagerService/Delete',
            v2_dot_kms_dot_kms__api__pb2.DeleteRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.KeyManagerService/Health',
            v2_dot_common_dot_common__message__pb2.HeartbeatRequest.SerializeToString,
            v2_dot_common_dot_common__message__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TopKServiceStub(object):
    """TopKService decrypts FHE encrypted scores and returns top-k results.
    Invariant I-2: no API accepts arbitrary FHE ciphertext for raw decryption.
    TopK produces application-level ranked results, not raw plaintext vectors.
    EncryptMetadata/DecryptMetadata operate on AES metadata, not FHE ciphertext.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TopK = channel.unary_unary(
                '/kms.v2.TopKService/TopK',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.TopKRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.TopKResponse.FromString,
                _registered_method=True)
        self.EncryptMetadata = channel.unary_unary(
                '/kms.v2.TopKService/EncryptMetadata',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.EncryptMetadataRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.EncryptMetadataResponse.FromString,
                _registered_method=True)
        self.DecryptMetadata = channel.unary_unary(
                '/kms.v2.TopKService/DecryptMetadata',
                request_serializer=v2_dot_kms_dot_kms__api__pb2.DecryptMetadataRequest.SerializeToString,
                response_deserializer=v2_dot_kms_dot_kms__api__pb2.DecryptMetadataResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kms.v2.TopKService/Health',
                request_serializer=v2_dot_common_dot_common__message__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=v2_dot_common_dot_common__message__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class TopKServiceServicer(object):
    """TopKService decrypts FHE encrypted scores and returns top-k results.
    Invariant I-2: no API accepts arbitrary FHE ciphertext for raw decryption.
    TopK produces application-level ranked results, not raw plaintext vectors.
    EncryptMetadata/DecryptMetadata operate on AES metadata, not FHE ciphertext.
    """

    def TopK(self, request, context):
        """Decrypt scores, filter by threshold, sort, return top-k results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptMetadata(self, request, context):
        """Encrypt plaintext metadata strings using the MetadataKey identified by
        key_id. MetadataKey never leaves KMS -- clients send plaintext, receive
        ciphertext.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptMetadata(self, request, context):
        """Decrypt metadata ciphertexts using the MetadataKey identified by key_id.
        MetadataKey never leaves KMS -- clients send ciphertext, receive plaintext.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopKServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TopK': grpc.unary_unary_rpc_method_handler(
                    servicer.TopK,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.TopKRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.TopKResponse.SerializeToString,
            ),
            'EncryptMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptMetadata,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.EncryptMetadataRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.EncryptMetadataResponse.SerializeToString,
            ),
            'DecryptMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptMetadata,
                    request_deserializer=v2_dot_kms_dot_kms__api__pb2.DecryptMetadataRequest.FromString,
                    response_serializer=v2_dot_kms_dot_kms__api__pb2.DecryptMetadataResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v2_dot_common_dot_common__message__pb2.HeartbeatRequest.FromString,
                    response_serializer=v2_dot_common_dot_common__message__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.v2.TopKService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kms.v2.TopKService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopKService(object):
    """TopKService decrypts FHE encrypted scores and returns top-k results.
    Invariant I-2: no API accepts arbitrary FHE ciphertext for raw decryption.
    TopK produces application-level ranked results, not raw plaintext vectors.
    EncryptMetadata/DecryptMetadata operate on AES metadata, not FHE ciphertext.
    """

    @staticmethod
    def TopK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.TopKService/TopK',
            v2_dot_kms_dot_kms__api__pb2.TopKRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.TopKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.TopKService/EncryptMetadata',
            v2_dot_kms_dot_kms__api__pb2.EncryptMetadataRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.EncryptMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.TopKService/DecryptMetadata',
            v2_dot_kms_dot_kms__api__pb2.DecryptMetadataRequest.SerializeToString,
            v2_dot_kms_dot_kms__api__pb2.DecryptMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kms.v2.TopKService/Health',
            v2_dot_common_dot_common__message__pb2.HeartbeatRequest.SerializeToString,
            v2_dot_common_dot_common__message__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
