# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/common/common-message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v2/common/common-message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import type_pb2 as v2_dot_common_dot_type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ev2/common/common-message.proto\x12\tcommon.v2\x1a\x14v2/common/type.proto\"T\n\rRequestHeader\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.common.v2.MessageType\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\"\xf5\x01\n\x0eResponseHeader\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.common.v2.MessageType\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12*\n\x0breturn_code\x18\x04 \x01(\x0e\x32\x15.common.v2.ReturnCode\x12\x1a\n\rerror_message\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tretryable\x18\x06 \x01(\x08H\x01\x88\x01\x01\x12\x13\n\x06\x61\x63tion\x18\x07 \x01(\tH\x02\x88\x01\x01\x42\x10\n\x0e_error_messageB\x0c\n\n_retryableB\t\n\x07_action\"<\n\x10HeartbeatRequest\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.common.v2.RequestHeader\">\n\x11HeartbeatResponse\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.common.v2.ResponseHeaderB\x1aZ\x18services/proto/common/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.common.common_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030services/proto/common/v2'
  _globals['_REQUESTHEADER']._serialized_start=67
  _globals['_REQUESTHEADER']._serialized_end=151
  _globals['_RESPONSEHEADER']._serialized_start=154
  _globals['_RESPONSEHEADER']._serialized_end=399
  _globals['_HEARTBEATREQUEST']._serialized_start=401
  _globals['_HEARTBEATREQUEST']._serialized_end=461
  _globals['_HEARTBEATRESPONSE']._serialized_start=463
  _globals['_HEARTBEATRESPONSE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
