# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/common/index-cluster-stats-message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v2/common/index-cluster-stats-message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_message_pb2 as v2_dot_common_dot_common__message__pb2
from . import type_pb2 as v2_dot_common_dot_type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+v2/common/index-cluster-stats-message.proto\x12\tcommon.v2\x1a\x1ev2/common/common-message.proto\x1a\x14v2/common/type.proto\"3\n\nShardStats\x12\x10\n\x08shard_id\x18\x01 \x01(\t\x12\x13\n\x0bnum_vectors\x18\x02 \x01(\x04\"I\n\x0c\x43lusterStats\x12\x12\n\ncluster_id\x18\x01 \x01(\x04\x12%\n\x06shards\x18\x02 \x03(\x0b\x32\x15.common.v2.ShardStats\"f\n\x0cVCTNodeStats\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\x12\x0f\n\x07is_leaf\x18\x03 \x01(\x08\x12%\n\x06shards\x18\x04 \x03(\x0b\x32\x15.common.v2.ShardStats\"[\n\x1bGetIndexClusterStatsRequest\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.common.v2.RequestHeader\x12\x12\n\nindex_name\x18\x02 \x01(\t\"\xf0\x01\n\x1cGetIndexClusterStatsResponse\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.common.v2.ResponseHeader\x12(\n\nindex_type\x18\x02 \x01(\x0e\x32\x14.common.v2.IndexType\x12\r\n\x05nlist\x18\x03 \x01(\x04\x12\x15\n\rtotal_vectors\x18\x04 \x01(\x04\x12)\n\x08\x63lusters\x18\x05 \x03(\x0b\x32\x17.common.v2.ClusterStats\x12*\n\tvct_nodes\x18\x06 \x03(\x0b\x32\x17.common.v2.VCTNodeStatsB\x1aZ\x18services/proto/common/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.common.index_cluster_stats_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030services/proto/common/v2'
  _globals['_SHARDSTATS']._serialized_start=112
  _globals['_SHARDSTATS']._serialized_end=163
  _globals['_CLUSTERSTATS']._serialized_start=165
  _globals['_CLUSTERSTATS']._serialized_end=238
  _globals['_VCTNODESTATS']._serialized_start=240
  _globals['_VCTNODESTATS']._serialized_end=342
  _globals['_GETINDEXCLUSTERSTATSREQUEST']._serialized_start=344
  _globals['_GETINDEXCLUSTERSTATSREQUEST']._serialized_end=435
  _globals['_GETINDEXCLUSTERSTATSRESPONSE']._serialized_start=438
  _globals['_GETINDEXCLUSTERSTATSRESPONSE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
