# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from ..common import index_cluster_stats_message_pb2 as v2_dot_common_dot_index__cluster__stats__message__pb2
from ..common import index_operation_message_pb2 as v2_dot_common_dot_index__operation__message__pb2
from . import endpoint_message_pb2 as v2_dot_endpoint_dot_endpoint__message__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v2/endpoint/endpoint_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EndpointServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_index = channel.stream_unary(
                '/endpoint.v2.EndpointService/create_index',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreateIndexResponse.FromString,
                _registered_method=True)
        self.get_index_list = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_index_list',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexListRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexListResponse.FromString,
                _registered_method=True)
        self.get_index_info = channel.unary_stream(
                '/endpoint.v2.EndpointService/get_index_info',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexInfoRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexInfoResponse.FromString,
                _registered_method=True)
        self.get_index_summary = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_index_summary',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexSummaryRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexSummaryResponse.FromString,
                _registered_method=True)
        self.get_index_operation_status = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_index_operation_status',
                request_serializer=v2_dot_common_dot_index__operation__message__pb2.GetIndexOperationStatusRequest.SerializeToString,
                response_deserializer=v2_dot_common_dot_index__operation__message__pb2.GetIndexOperationStatusResponse.FromString,
                _registered_method=True)
        self.get_index_cluster_stats = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_index_cluster_stats',
                request_serializer=v2_dot_common_dot_index__cluster__stats__message__pb2.GetIndexClusterStatsRequest.SerializeToString,
                response_deserializer=v2_dot_common_dot_index__cluster__stats__message__pb2.GetIndexClusterStatsResponse.FromString,
                _registered_method=True)
        self.load_index = channel.unary_unary(
                '/endpoint.v2.EndpointService/load_index',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadIndexRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadIndexResponse.FromString,
                _registered_method=True)
        self.unload_index = channel.unary_unary(
                '/endpoint.v2.EndpointService/unload_index',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadIndexRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadIndexResponse.FromString,
                _registered_method=True)
        self.delete_index = channel.unary_unary(
                '/endpoint.v2.EndpointService/delete_index',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteIndexRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteIndexResponse.FromString,
                _registered_method=True)
        self.clone_index = channel.unary_unary(
                '/endpoint.v2.EndpointService/clone_index',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CloneIndexRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CloneIndexResponse.FromString,
                _registered_method=True)
        self.create_partition = channel.unary_unary(
                '/endpoint.v2.EndpointService/create_partition',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreatePartitionRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreatePartitionResponse.FromString,
                _registered_method=True)
        self.drop_partition = channel.unary_unary(
                '/endpoint.v2.EndpointService/drop_partition',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DropPartitionRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DropPartitionResponse.FromString,
                _registered_method=True)
        self.list_partitions = channel.unary_unary(
                '/endpoint.v2.EndpointService/list_partitions',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListPartitionsRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListPartitionsResponse.FromString,
                _registered_method=True)
        self.register_key = channel.stream_unary(
                '/endpoint.v2.EndpointService/register_key',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.RegisterKeyRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.RegisterKeyResponse.FromString,
                _registered_method=True)
        self.get_key_list = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_key_list',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyListRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyListResponse.FromString,
                _registered_method=True)
        self.get_key_info = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_key_info',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyInfoRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyInfoResponse.FromString,
                _registered_method=True)
        self.load_key = channel.unary_unary(
                '/endpoint.v2.EndpointService/load_key',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadKeyRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadKeyResponse.FromString,
                _registered_method=True)
        self.unload_key = channel.unary_unary(
                '/endpoint.v2.EndpointService/unload_key',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadKeyRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadKeyResponse.FromString,
                _registered_method=True)
        self.delete_key = channel.unary_unary(
                '/endpoint.v2.EndpointService/delete_key',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteKeyRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteKeyResponse.FromString,
                _registered_method=True)
        self.insert_data = channel.stream_unary(
                '/endpoint.v2.EndpointService/insert_data',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataResponse.FromString,
                _registered_method=True)
        self.delete_data = channel.unary_unary(
                '/endpoint.v2.EndpointService/delete_data',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteDataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteDataResponse.FromString,
                _registered_method=True)
        self.batch_insert_data = channel.stream_unary(
                '/endpoint.v2.EndpointService/batch_insert_data',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataResponse.FromString,
                _registered_method=True)
        self.persist_rows = channel.stream_unary(
                '/endpoint.v2.EndpointService/persist_rows',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataResponse.FromString,
                _registered_method=True)
        self.persist_batch = channel.stream_unary(
                '/endpoint.v2.EndpointService/persist_batch',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataResponse.FromString,
                _registered_method=True)
        self.merge_by_request_ids = channel.unary_unary(
                '/endpoint.v2.EndpointService/merge_by_request_ids',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.MergeByRequestIdsRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.MergeByRequestIdsResponse.FromString,
                _registered_method=True)
        self.inner_product = channel.unary_stream(
                '/endpoint.v2.EndpointService/inner_product',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.InnerProductRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.InnerProductResponse.FromString,
                _registered_method=True)
        self.get_metadata = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_metadata',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.update_metadata = channel.unary_unary(
                '/endpoint.v2.EndpointService/update_metadata',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UpdateMetadataResponse.FromString,
                _registered_method=True)
        self.export_system = channel.unary_stream(
                '/endpoint.v2.EndpointService/export_system',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.ExportSystemRequest.SerializeToString,
                response_deserializer=google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
                _registered_method=True)
        self.preflight_import = channel.unary_unary(
                '/endpoint.v2.EndpointService/preflight_import',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.PreflightImportRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.PreflightImportResponse.FromString,
                _registered_method=True)
        self.upload_import_part = channel.unary_unary(
                '/endpoint.v2.EndpointService/upload_import_part',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UploadImportPartRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UploadImportPartResponse.FromString,
                _registered_method=True)
        self.commit_import = channel.unary_unary(
                '/endpoint.v2.EndpointService/commit_import',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CommitImportRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CommitImportResponse.FromString,
                _registered_method=True)
        self.delete_import = channel.unary_unary(
                '/endpoint.v2.EndpointService/delete_import',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteImportRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteImportResponse.FromString,
                _registered_method=True)
        self.get_import_status = channel.unary_unary(
                '/endpoint.v2.EndpointService/get_import_status',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetImportStatusRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetImportStatusResponse.FromString,
                _registered_method=True)
        self.list_imports = channel.unary_unary(
                '/endpoint.v2.EndpointService/list_imports',
                request_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListImportsRequest.SerializeToString,
                response_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListImportsResponse.FromString,
                _registered_method=True)


class EndpointServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_index(self, request_iterator, context):
        """Index-related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_index_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_index_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_index_summary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_index_operation_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_index_cluster_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unload_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clone_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_partition(self, request, context):
        """Partition-related (named partitions within an index).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def drop_partition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_partitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register_key(self, request_iterator, context):
        """Key-related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_key_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_key_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unload_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_data(self, request_iterator, context):
        """Others
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_data(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batch_insert_data(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def persist_rows(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def persist_batch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def merge_by_request_ids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def inner_product(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_metadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_metadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def export_system(self, request, context):
        """Backup / Restore (Phase 1 — system scope, multi-part bundle, admin-only).

        Export: server tars the bundle directory and emits as a single response
        body; client typically pipes into `tar -xz -C ./bundle-{ts}/`.
        Returns stream<google.api.HttpBody> so grpc-gateway forwards raw tar
        bytes without JSON/base64 wrapping. bundle_root_sha256 + bundle_version
        travel inside the bundle (manifest.json, the last tar entry — written
        after all parts so the catalog can include their sha256 chain); the
        client computes total bytes locally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def preflight_import(self, request, context):
        """Import core (three-step protocol over multi-part bundle).

        PreflightImport: creates a new import resource — validates manifest,
        performs idempotency lookup, allocates import_id, INSERTs import_log +
        import_log_parts rows, and starts the expiry timer. REST path follows
        standard collection-POST = create-resource convention. Body is the
        full request including manifest_json (raw JSON bytes carried in the
        proto bytes field; encoded as base64 in JSON wire format).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload_import_part(self, request, context):
        """UploadImportPart: PUT a single part. The part_path captures the bundle
        path including slashes via the wildcard `**`. Path-traversal defense
        (§12.6) validates the captured path against the manifest catalog before
        the server accepts any byte. expected_sha256 / expected_size travel as
        query string parameters in the REST surface (grpc-gateway default
        json_name camelCase, e.g.,
        `?expectedSha256=abc...&expectedSize=104857600`); gRPC clients fill the
        proto fields directly. The HTTP request body becomes the `data` field
        (google.api.HttpBody) — raw bytes, no JSON/base64 wrapping.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def commit_import(self, request, context):
        """CommitImport: run the import transaction and flip status to active.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_import(self, request, context):
        """Import operations (admin tooling).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_import_status(self, request, context):
        """GetImportStatus: return the lifecycle state and progress (parts received,
        bytes received, expiry) of one import. Polling-friendly (recommended
        interval 5–10s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_imports(self, request, context):
        """ListImports: return recent import_log rows (descending by created_at,
        pageable). Useful for operator dashboards and post-mortem inspection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EndpointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_index': grpc.stream_unary_rpc_method_handler(
                    servicer.create_index,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreateIndexRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreateIndexResponse.SerializeToString,
            ),
            'get_index_list': grpc.unary_unary_rpc_method_handler(
                    servicer.get_index_list,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexListRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexListResponse.SerializeToString,
            ),
            'get_index_info': grpc.unary_stream_rpc_method_handler(
                    servicer.get_index_info,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexInfoRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexInfoResponse.SerializeToString,
            ),
            'get_index_summary': grpc.unary_unary_rpc_method_handler(
                    servicer.get_index_summary,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexSummaryRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexSummaryResponse.SerializeToString,
            ),
            'get_index_operation_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_index_operation_status,
                    request_deserializer=v2_dot_common_dot_index__operation__message__pb2.GetIndexOperationStatusRequest.FromString,
                    response_serializer=v2_dot_common_dot_index__operation__message__pb2.GetIndexOperationStatusResponse.SerializeToString,
            ),
            'get_index_cluster_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_index_cluster_stats,
                    request_deserializer=v2_dot_common_dot_index__cluster__stats__message__pb2.GetIndexClusterStatsRequest.FromString,
                    response_serializer=v2_dot_common_dot_index__cluster__stats__message__pb2.GetIndexClusterStatsResponse.SerializeToString,
            ),
            'load_index': grpc.unary_unary_rpc_method_handler(
                    servicer.load_index,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadIndexRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadIndexResponse.SerializeToString,
            ),
            'unload_index': grpc.unary_unary_rpc_method_handler(
                    servicer.unload_index,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadIndexRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadIndexResponse.SerializeToString,
            ),
            'delete_index': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_index,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteIndexRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteIndexResponse.SerializeToString,
            ),
            'clone_index': grpc.unary_unary_rpc_method_handler(
                    servicer.clone_index,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CloneIndexRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CloneIndexResponse.SerializeToString,
            ),
            'create_partition': grpc.unary_unary_rpc_method_handler(
                    servicer.create_partition,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreatePartitionRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CreatePartitionResponse.SerializeToString,
            ),
            'drop_partition': grpc.unary_unary_rpc_method_handler(
                    servicer.drop_partition,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DropPartitionRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DropPartitionResponse.SerializeToString,
            ),
            'list_partitions': grpc.unary_unary_rpc_method_handler(
                    servicer.list_partitions,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListPartitionsRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListPartitionsResponse.SerializeToString,
            ),
            'register_key': grpc.stream_unary_rpc_method_handler(
                    servicer.register_key,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.RegisterKeyRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.RegisterKeyResponse.SerializeToString,
            ),
            'get_key_list': grpc.unary_unary_rpc_method_handler(
                    servicer.get_key_list,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyListRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyListResponse.SerializeToString,
            ),
            'get_key_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_key_info,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyInfoRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyInfoResponse.SerializeToString,
            ),
            'load_key': grpc.unary_unary_rpc_method_handler(
                    servicer.load_key,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadKeyRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.LoadKeyResponse.SerializeToString,
            ),
            'unload_key': grpc.unary_unary_rpc_method_handler(
                    servicer.unload_key,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadKeyRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UnloadKeyResponse.SerializeToString,
            ),
            'delete_key': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_key,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteKeyRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteKeyResponse.SerializeToString,
            ),
            'insert_data': grpc.stream_unary_rpc_method_handler(
                    servicer.insert_data,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataResponse.SerializeToString,
            ),
            'delete_data': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_data,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteDataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteDataResponse.SerializeToString,
            ),
            'batch_insert_data': grpc.stream_unary_rpc_method_handler(
                    servicer.batch_insert_data,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataResponse.SerializeToString,
            ),
            'persist_rows': grpc.stream_unary_rpc_method_handler(
                    servicer.persist_rows,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataResponse.SerializeToString,
            ),
            'persist_batch': grpc.stream_unary_rpc_method_handler(
                    servicer.persist_batch,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataResponse.SerializeToString,
            ),
            'merge_by_request_ids': grpc.unary_unary_rpc_method_handler(
                    servicer.merge_by_request_ids,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.MergeByRequestIdsRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.MergeByRequestIdsResponse.SerializeToString,
            ),
            'inner_product': grpc.unary_stream_rpc_method_handler(
                    servicer.inner_product,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.InnerProductRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.InnerProductResponse.SerializeToString,
            ),
            'get_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.get_metadata,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetMetadataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetMetadataResponse.SerializeToString,
            ),
            'update_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.update_metadata,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UpdateMetadataResponse.SerializeToString,
            ),
            'export_system': grpc.unary_stream_rpc_method_handler(
                    servicer.export_system,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.ExportSystemRequest.FromString,
                    response_serializer=google_dot_api_dot_httpbody__pb2.HttpBody.SerializeToString,
            ),
            'preflight_import': grpc.unary_unary_rpc_method_handler(
                    servicer.preflight_import,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.PreflightImportRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.PreflightImportResponse.SerializeToString,
            ),
            'upload_import_part': grpc.unary_unary_rpc_method_handler(
                    servicer.upload_import_part,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.UploadImportPartRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.UploadImportPartResponse.SerializeToString,
            ),
            'commit_import': grpc.unary_unary_rpc_method_handler(
                    servicer.commit_import,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.CommitImportRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.CommitImportResponse.SerializeToString,
            ),
            'delete_import': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_import,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteImportRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.DeleteImportResponse.SerializeToString,
            ),
            'get_import_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_import_status,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetImportStatusRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.GetImportStatusResponse.SerializeToString,
            ),
            'list_imports': grpc.unary_unary_rpc_method_handler(
                    servicer.list_imports,
                    request_deserializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListImportsRequest.FromString,
                    response_serializer=v2_dot_endpoint_dot_endpoint__message__pb2.ListImportsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoint.v2.EndpointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('endpoint.v2.EndpointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EndpointService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_index(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/endpoint.v2.EndpointService/create_index',
            v2_dot_endpoint_dot_endpoint__message__pb2.CreateIndexRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.CreateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_index_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_index_list',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexListRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_index_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/endpoint.v2.EndpointService/get_index_info',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexInfoRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_index_summary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_index_summary',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexSummaryRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetIndexSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_index_operation_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_index_operation_status',
            v2_dot_common_dot_index__operation__message__pb2.GetIndexOperationStatusRequest.SerializeToString,
            v2_dot_common_dot_index__operation__message__pb2.GetIndexOperationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_index_cluster_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_index_cluster_stats',
            v2_dot_common_dot_index__cluster__stats__message__pb2.GetIndexClusterStatsRequest.SerializeToString,
            v2_dot_common_dot_index__cluster__stats__message__pb2.GetIndexClusterStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def load_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/load_index',
            v2_dot_endpoint_dot_endpoint__message__pb2.LoadIndexRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.LoadIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unload_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/unload_index',
            v2_dot_endpoint_dot_endpoint__message__pb2.UnloadIndexRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.UnloadIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/delete_index',
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteIndexRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def clone_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/clone_index',
            v2_dot_endpoint_dot_endpoint__message__pb2.CloneIndexRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.CloneIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_partition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/create_partition',
            v2_dot_endpoint_dot_endpoint__message__pb2.CreatePartitionRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.CreatePartitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def drop_partition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/drop_partition',
            v2_dot_endpoint_dot_endpoint__message__pb2.DropPartitionRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.DropPartitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def list_partitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/list_partitions',
            v2_dot_endpoint_dot_endpoint__message__pb2.ListPartitionsRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.ListPartitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def register_key(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/endpoint.v2.EndpointService/register_key',
            v2_dot_endpoint_dot_endpoint__message__pb2.RegisterKeyRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.RegisterKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_key_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_key_list',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyListRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_key_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_key_info',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyInfoRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetKeyInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def load_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/load_key',
            v2_dot_endpoint_dot_endpoint__message__pb2.LoadKeyRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.LoadKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unload_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/unload_key',
            v2_dot_endpoint_dot_endpoint__message__pb2.UnloadKeyRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.UnloadKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/delete_key',
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteKeyRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_data(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/endpoint.v2.EndpointService/insert_data',
            v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/delete_data',
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteDataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def batch_insert_data(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/endpoint.v2.EndpointService/batch_insert_data',
            v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def persist_rows(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/endpoint.v2.EndpointService/persist_rows',
            v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.InsertDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def persist_batch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/endpoint.v2.EndpointService/persist_batch',
            v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.BatchInsertDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def merge_by_request_ids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/merge_by_request_ids',
            v2_dot_endpoint_dot_endpoint__message__pb2.MergeByRequestIdsRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.MergeByRequestIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def inner_product(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/endpoint.v2.EndpointService/inner_product',
            v2_dot_endpoint_dot_endpoint__message__pb2.InnerProductRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.InnerProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_metadata',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetMetadataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/update_metadata',
            v2_dot_endpoint_dot_endpoint__message__pb2.UpdateMetadataRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def export_system(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/endpoint.v2.EndpointService/export_system',
            v2_dot_endpoint_dot_endpoint__message__pb2.ExportSystemRequest.SerializeToString,
            google_dot_api_dot_httpbody__pb2.HttpBody.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def preflight_import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/preflight_import',
            v2_dot_endpoint_dot_endpoint__message__pb2.PreflightImportRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.PreflightImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def upload_import_part(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/upload_import_part',
            v2_dot_endpoint_dot_endpoint__message__pb2.UploadImportPartRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.UploadImportPartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def commit_import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/commit_import',
            v2_dot_endpoint_dot_endpoint__message__pb2.CommitImportRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.CommitImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/delete_import',
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteImportRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.DeleteImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_import_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/get_import_status',
            v2_dot_endpoint_dot_endpoint__message__pb2.GetImportStatusRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.GetImportStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def list_imports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/endpoint.v2.EndpointService/list_imports',
            v2_dot_endpoint_dot_endpoint__message__pb2.ListImportsRequest.SerializeToString,
            v2_dot_endpoint_dot_endpoint__message__pb2.ListImportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
