# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audit_message_pb2 as v2_dot_audit_dot_audit__message__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v2/audit/audit_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub(object):
    """AuditService exposes the dedicated audit-plane APIs.
    The service is intended to run as a standalone process/container rather than
    being embedded in the endpoint data plane.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_events = channel.unary_unary(
                '/audit.v2.AuditService/list_events',
                request_serializer=v2_dot_audit_dot_audit__message__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=v2_dot_audit_dot_audit__message__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.export_events = channel.unary_stream(
                '/audit.v2.AuditService/export_events',
                request_serializer=v2_dot_audit_dot_audit__message__pb2.ExportEventsRequest.SerializeToString,
                response_deserializer=v2_dot_audit_dot_audit__message__pb2.ExportEventsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """AuditService exposes the dedicated audit-plane APIs.
    The service is intended to run as a standalone process/container rather than
    being embedded in the endpoint data plane.
    """

    def list_events(self, request, context):
        """Lists audit events with filtering and pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def export_events(self, request, context):
        """Streams exported audit events in the requested format.
        The standalone skeleton wires JSON export first; other formats are
        reserved for follow-up phases.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_events': grpc.unary_unary_rpc_method_handler(
                    servicer.list_events,
                    request_deserializer=v2_dot_audit_dot_audit__message__pb2.ListEventsRequest.FromString,
                    response_serializer=v2_dot_audit_dot_audit__message__pb2.ListEventsResponse.SerializeToString,
            ),
            'export_events': grpc.unary_stream_rpc_method_handler(
                    servicer.export_events,
                    request_deserializer=v2_dot_audit_dot_audit__message__pb2.ExportEventsRequest.FromString,
                    response_serializer=v2_dot_audit_dot_audit__message__pb2.ExportEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audit.v2.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audit.v2.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """AuditService exposes the dedicated audit-plane APIs.
    The service is intended to run as a standalone process/container rather than
    being embedded in the endpoint data plane.
    """

    @staticmethod
    def list_events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v2.AuditService/list_events',
            v2_dot_audit_dot_audit__message__pb2.ListEventsRequest.SerializeToString,
            v2_dot_audit_dot_audit__message__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def export_events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/audit.v2.AuditService/export_events',
            v2_dot_audit_dot_audit__message__pb2.ExportEventsRequest.SerializeToString,
            v2_dot_audit_dot_audit__message__pb2.ExportEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
