# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/audit/audit-type.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v2/audit/audit-type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19v2/audit/audit-type.proto\x12\x08\x61udit.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x04\n\nAuditEvent\x12\x1c\n\x14\x61udit_schema_version\x18\x01 \x01(\x05\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11\x63laimed_tenant_id\x18\n \x01(\t\x12\x17\n\x0f\x63laimed_user_id\x18\x0b \x01(\t\x12\x17\n\x0fidentity_source\x18\x0c \x01(\t\x12\x0f\n\x07jwt_kid\x18\r \x01(\t\x12\x0f\n\x07jwt_iss\x18\x0e \x01(\t\x12\x0f\n\x07jwt_aud\x18\x0f \x01(\t\x12\r\n\x05\x61\x63tor\x18\x10 \x01(\t\x12\x0c\n\x04role\x18\x11 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x14 \x01(\t\x12\x10\n\x08resource\x18\x15 \x01(\t\x12\x13\n\x0b\x66ull_method\x18\x16 \x01(\t\x12\x12\n\nindex_name\x18\x1e \x01(\t\x12\x0e\n\x06key_id\x18\x1f \x01(\t\x12\x12\n\ncontext_id\x18  \x01(\t\x12\x10\n\x08shard_id\x18! \x01(\t\x12\x12\n\nrequest_id\x18\" \x01(\t\x12\x10\n\x08trace_id\x18# \x01(\t\x12\x0e\n\x06result\x18( \x01(\t\x12\x13\n\x0b\x64uration_ms\x18) \x01(\x03\x12\r\n\x05\x65rror\x18* \x01(\t\x12\x11\n\tgrpc_code\x18+ \x01(\t\x12\x11\n\tclient_ip\x18\x32 \x01(\t\x12\x14\n\x0cpeer_address\x18\x33 \x01(\t\x12\x13\n\x0b\x61uth_scheme\x18\x34 \x01(\t\x12\x18\n\x10\x61uth_fingerprint\x18\x35 \x01(\t*w\n\x0c\x45xportFormat\x12\x1d\n\x19\x45XPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n\x12\x45XPORT_FORMAT_JSON\x10\x01\x12\x15\n\x11\x45XPORT_FORMAT_CSV\x10\x02\x12\x19\n\x15\x45XPORT_FORMAT_PARQUET\x10\x03\x42\x19Z\x17services/proto/audit/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.audit.audit_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027services/proto/audit/v2'
  _globals['_EXPORTFORMAT']._serialized_start=647
  _globals['_EXPORTFORMAT']._serialized_end=766
  _globals['_AUDITEVENT']._serialized_start=73
  _globals['_AUDITEVENT']._serialized_end=645
# @@protoc_insertion_point(module_scope)
