# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/audit/audit-api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v2/audit/audit-api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from . import audit_message_pb2 as v2_dot_audit_dot_audit__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v2/audit/audit-api.proto\x12\x08\x61udit.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1cv2/audit/audit-message.proto2\xeb\x01\n\x0c\x41uditService\x12\x65\n\x0blist_events\x12\x1b.audit.v2.ListEventsRequest\x1a\x1c.audit.v2.ListEventsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v2/audit/events:\x01*\x12t\n\rexport_events\x12\x1d.audit.v2.ExportEventsRequest\x1a\x1e.audit.v2.ExportEventsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v2/audit/events/export:\x01*0\x01\x42\x19Z\x17services/proto/audit/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.audit.audit_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027services/proto/audit/v2'
  _globals['_AUDITSERVICE'].methods_by_name['list_events']._loaded_options = None
  _globals['_AUDITSERVICE'].methods_by_name['list_events']._serialized_options = b'\202\323\344\223\002\025\"\020/v2/audit/events:\001*'
  _globals['_AUDITSERVICE'].methods_by_name['export_events']._loaded_options = None
  _globals['_AUDITSERVICE'].methods_by_name['export_events']._serialized_options = b'\202\323\344\223\002\034\"\027/v2/audit/events/export:\001*'
  _globals['_AUDITSERVICE']._serialized_start=99
  _globals['_AUDITSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
