# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/audit/audit-message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v2/audit/audit-message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import audit_type_pb2 as v2_dot_audit_dot_audit__type__pb2
from ..common import common_message_pb2 as v2_dot_common_dot_common__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cv2/audit/audit-message.proto\x12\x08\x61udit.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19v2/audit/audit-type.proto\x1a\x1ev2/common/common-message.proto\"\xf8\x01\n\x11ListEventsRequest\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.common.v2.RequestHeader\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x61\x63tions\x18\x04 \x03(\t\x12\x0e\n\x06\x61\x63tors\x18\x05 \x03(\t\x12\x13\n\x0bindex_names\x18\x06 \x03(\t\x12\x12\n\npage_token\x18\x07 \x01(\t\x12\x11\n\tpage_size\x18\x08 \x01(\x05\"\x93\x01\n\x12ListEventsResponse\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.common.v2.ResponseHeader\x12$\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x14.audit.v2.AuditEvent\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t\x12\x13\n\x0btotal_count\x18\x04 \x01(\x03\"\xfb\x01\n\x13\x45xportEventsRequest\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.common.v2.RequestHeader\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x61\x63tions\x18\x04 \x03(\t\x12\x0e\n\x06\x61\x63tors\x18\x05 \x03(\t\x12\x13\n\x0bindex_names\x18\x06 \x03(\t\x12&\n\x06\x66ormat\x18\x07 \x01(\x0e\x32\x16.audit.v2.ExportFormat\"a\n\x14\x45xportEventsResponse\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.common.v2.ResponseHeader\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\x42\x19Z\x17services/proto/audit/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.audit.audit_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027services/proto/audit/v2'
  _globals['_LISTEVENTSREQUEST']._serialized_start=135
  _globals['_LISTEVENTSREQUEST']._serialized_end=383
  _globals['_LISTEVENTSRESPONSE']._serialized_start=386
  _globals['_LISTEVENTSRESPONSE']._serialized_end=533
  _globals['_EXPORTEVENTSREQUEST']._serialized_start=536
  _globals['_EXPORTEVENTSREQUEST']._serialized_end=787
  _globals['_EXPORTEVENTSRESPONSE']._serialized_start=789
  _globals['_EXPORTEVENTSRESPONSE']._serialized_end=886
# @@protoc_insertion_point(module_scope)
